-- ============================================================================
-- NASA Space Events Dashboard - Updated Database Schema
-- Compatible with: Spring Boot Entities (JPA)
-- ============================================================================

-- 0. API_SOURCE (Metadata table for tracking data sources)
CREATE TABLE api_source (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            source_name VARCHAR(50) UNIQUE NOT NULL,
                            url VARCHAR(255),
                            description TEXT,
                            last_fetch_time TIMESTAMP,
                            total_records_fetched BIGINT DEFAULT 0
);

-- 1. SOLAR_FLARE
CREATE TABLE solar_flare (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             activity_id VARCHAR(50) UNIQUE,

    -- Temporal
                             begin_time TIMESTAMP,
                             peak_time TIMESTAMP NOT NULL,
                             end_time TIMESTAMP,
                             submission_time TIMESTAMP,

    -- Classification
                             class_type VARCHAR(2),          -- 'X', 'M', 'C'
                             class_intensity DECIMAL(6, 2),  -- 2.5
                             full_class VARCHAR(10),         -- 'X2.5'

    -- Location & Source
                             source_location VARCHAR(10),
                             active_region_num INTEGER,

    -- Metadata
                             instruments TEXT,
                             note TEXT,
                             linked_events TEXT,             -- JSON Array
                             version_id INTEGER,
                             raw_data TEXT,

    -- Relations
                             api_source_id BIGINT REFERENCES api_source(id),
                             created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_flare_peak ON solar_flare(peak_time);
CREATE INDEX idx_flare_class ON solar_flare(class_type, class_intensity);

-- 2. CORONAL_MASS_EJECTION
CREATE TABLE coronal_mass_ejection (
                                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       activity_id VARCHAR(50) UNIQUE,

    -- Temporal
                                       start_time TIMESTAMP NOT NULL,
                                       submission_time TIMESTAMP,

    -- Physical
                                       speed_km_s DECIMAL(10, 2),
                                       half_angle_deg DECIMAL(6, 2),
                                       type VARCHAR(20),

    -- Location
                                       latitude DECIMAL(6, 2),
                                       longitude DECIMAL(6, 2),
                                       source_location VARCHAR(10),

    -- Analysis Details (New Fields)
                                       is_most_accurate BOOLEAN DEFAULT FALSE,
                                       time_21_5 TIMESTAMP,
                                       feature_code VARCHAR(10),
                                       image_type VARCHAR(50),
                                       measurement_technique VARCHAR(100),
                                       level_of_data INTEGER,
                                       tilt DECIMAL(10, 2),
                                       minor_half_width DECIMAL(10, 2),
                                       speed_measured_at_height DECIMAL(10, 2),

    -- Metadata
                                       instruments TEXT,
                                       note TEXT,
                                       linked_events TEXT,
                                       version_id INTEGER,
                                       raw_data TEXT,

    -- Relations
                                       api_source_id BIGINT REFERENCES api_source(id),
                                       created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_cme_time ON coronal_mass_ejection(start_time);
CREATE INDEX idx_cme_speed ON coronal_mass_ejection(speed_km_s);

-- 3. GEOMAGNETIC_STORM
CREATE TABLE geomagnetic_storm (
                                   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   activity_id VARCHAR(50) UNIQUE,

    -- Temporal
                                   start_time TIMESTAMP NOT NULL,
                                   end_time TIMESTAMP,
                                   submission_time TIMESTAMP,

    -- Intensity
                                   kp_index DECIMAL(3, 1),
                                   dst_index INTEGER,
                                   g_scale INTEGER,                -- Calcolato automaticamente (1-5)

    -- Metadata
                                   all_kp_index TEXT,              -- JSON Array with full timeline
                                   instruments TEXT,
                                   linked_events TEXT,
                                   version_id INTEGER,
                                   raw_data TEXT,

    -- Relations
                                   api_source_id BIGINT REFERENCES api_source(id),
                                   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_gst_start ON geomagnetic_storm(start_time);
CREATE INDEX idx_gst_kp ON geomagnetic_storm(kp_index);

-- 4. INTERPLANETARY_SHOCK
CREATE TABLE interplanetary_shock (
                                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      activity_id VARCHAR(100) UNIQUE,
                                      catalog VARCHAR(50),

    -- Temporal
                                      activity_time TIMESTAMP NOT NULL,
                                      submission_time TIMESTAMP,

    -- Location
                                      location VARCHAR(50),           -- 'Earth', 'STEREO A'

    -- Metadata
                                      instruments TEXT,
                                      linked_events TEXT,
                                      version_id INTEGER,
                                      raw_data TEXT,

    -- Relations
                                      api_source_id BIGINT REFERENCES api_source(id),
                                      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_ips_time ON interplanetary_shock(activity_time);
CREATE INDEX idx_ips_location ON interplanetary_shock(location);

-- 5. FIREBALL
CREATE TABLE fireball (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Temporal
                          event_date TIMESTAMP NOT NULL,

    -- Location
                          latitude DECIMAL(9, 6),
                          longitude DECIMAL(9, 6),
                          altitude_km DECIMAL(8, 2),

    -- Energy & Velocity
                          total_radiated_energy_j DECIMAL(15, 2),
                          total_impact_energy_kt DECIMAL(10, 4),
                          velocity_km_s DECIMAL(8, 2),

    -- Vector Velocity (New Fields)
                          velocity_vx DECIMAL(10, 2),
                          velocity_vy DECIMAL(10, 2),
                          velocity_vz DECIMAL(10, 2),

    -- Metadata
                          raw_data TEXT,
                          api_source_id BIGINT REFERENCES api_source(id),
                          created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_fireball_date ON fireball(event_date);
CREATE INDEX idx_fireball_location ON fireball(latitude, longitude);

-- 6. NEO_ASTEROID (Parent Table)
CREATE TABLE neo_asteroid (
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              neo_reference_id VARCHAR(20) UNIQUE NOT NULL,
                              name VARCHAR(100) NOT NULL,

    -- Hazard
                              is_potentially_hazardous BOOLEAN DEFAULT FALSE,
                              is_sentry_object BOOLEAN DEFAULT FALSE,

    -- Physical
                              absolute_magnitude_h DECIMAL(6, 2),
                              estimated_diameter_km_min DECIMAL(10, 4),
                              estimated_diameter_km_max DECIMAL(10, 4),
                              estimated_diameter_m_min DECIMAL(10, 2),
                              estimated_diameter_m_max DECIMAL(10, 2),

    -- Orbital
                              orbital_period_days DECIMAL(12, 2),
                              orbit_eccentricity DECIMAL(10, 8),
                              semi_major_axis_au DECIMAL(12, 8),
                              inclination_deg DECIMAL(8, 4),
                              first_observation_date DATE,
                              last_observation_date DATE,

    -- Metadata
                              nasa_jpl_url TEXT,
                              raw_data TEXT,
                              api_source_id BIGINT REFERENCES api_source(id),
                              created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_neo_hazardous ON neo_asteroid(is_potentially_hazardous);
CREATE INDEX idx_neo_magnitude ON neo_asteroid(absolute_magnitude_h);

-- 7. NEO_CLOSE_APPROACH (Child Table - One Asteroid has Many Approaches)
CREATE TABLE neo_close_approach (
                                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Relation
                                    neo_id BIGINT NOT NULL REFERENCES neo_asteroid(id),

    -- Temporal
                                    approach_date TIMESTAMP NOT NULL,

    -- Distance
                                    miss_distance_km DECIMAL(15, 2),
                                    miss_distance_au DECIMAL(12, 8),
                                    miss_distance_lunar DECIMAL(10, 2),

    -- Velocity
                                    relative_velocity_km_s DECIMAL(10, 2),
                                    relative_velocity_km_h DECIMAL(12, 2),

                                    orbiting_body VARCHAR(20) DEFAULT 'Earth',
                                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_approach_date ON neo_close_approach(approach_date);
CREATE INDEX idx_approach_neo ON neo_close_approach(neo_id);
